[package]
name = "invil"
description = "A port of amboso to Rust"
version = "0.2.1-dev"
edition = "2021"
license = "GPL-3.0-only"
homepage = "https://github.com/jgabaut/invil"
repository = "https://github.com/jgabaut/invil"
documentation = "https://github.com/jgabaut/amboso"
readme = "README.md"
exclude = [
    ".github/**",
    "try-anvil/**",
    "CODEOWNERS",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
git2 = "0.18.1"
is_executable = "1.0.1"
log = "0.4.20"
regex = "1.10.2"
simplelog = "0.12.1"
toml = "0.8.8"
