[package]
name = "invil"
description = "A port of amboso to Rust"
version = "0.2.8"
edition = "2021"
license = "GPL-3.0-only"
homepage = "https://github.com/jgabaut/invil"
repository = "https://github.com/jgabaut/invil"
documentation = "https://github.com/jgabaut/amboso"
readme = "README.md"
exclude = [
    ".github/**",
    "try-anvil/**",
    "CODEOWNERS",
    "bin/",
    "stego.lock",
    "kazoj",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
flate2 = "1.0.28"
git2 = "0.18.2"
is_executable = "1.0.1"
log = "0.4.20"
regex = "1.10.3"
simplelog = "0.12.1"
tar = "0.4.40"
toml = "0.8.10"
url = "2.5.0"
