[package]
name = "invil"
description = "A port of amboso to Rust"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
homepage = "https://github.com/jgabaut/invil"
repository = "https://github.com/jgabaut/invil"
documentation = "https://github.com/jgabaut/invil"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
log = "0.4.20"
simplelog = "0.12.1"
toml = "0.8.8"
